# Generated by Django 4.0.3 on 2022-03-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_rename_user_profile_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
